In [1]:
import os
import scipy.io as sio
import cv2
import numpy as np
DEBUG = False
SIZE = 224
PATH = '/home/zxy/Datasets/pascal3d/'
ANNOT_PATH = PATH + 'Annotations/'
IMAGE_PATH = PATH + 'Images/'
SAVE_PATH = PATH + 'Pascal3D/'
if not os.path.exists(SAVE_PATH):
    os.mkdir(SAVE_PATH)


In [2]:
objs = os.listdir(ANNOT_PATH)

In [4]:
for obj in objs:
    obj_path = SAVE_PATH + obj
    if not os.path.exists(obj_path):
        os.mkdir(obj_path)
    view_file = open(obj_path + 'annots.txt', 'w')
    img_path = IMAGE_PATH + obj
    for im_name in os.listdir(img_path):
        obj_id = im_name.split('.')[0]
        annot_file = ANNOT_PATH + obj + '/' + obj_id
        data = sio.loadmat(annot_file)
        data_objects = data['record']['objects'][0][0]
        cls = data_objects['class'][0]
        bbox = data_objects['bbox'][0]
        viewpoint = data_objects['viewpoint'][0]
        img = cv2.imread(img_path + '/' + im_name)
        
        #
        #print 'bbox', bbox, bbox.shape
        #print 'viewpoint', viewpoint, viewpoint.shape
        
        pad = max(img.shape[0], img.shape[1])
        pad_img = np.zeros((img.shape[0] + pad * 2, img.shape[1] + pad * 2, 3), dtype = np.uint8)
        pad_img[pad:pad+img.shape[0], pad:pad+img.shape[1]] = img.copy()
        
        if DEBUG:
            cv2.imshow('img', img)
        cnt = 0
        for i in range(bbox.shape[0]):
            #print cls[i][0]
            if not (cls[i][0] in obj):
                continue
            box = bbox[i][0]
            l = int(max(box[2] - box[0], box[3] - box[1]) * 1.2)
            ct = [(box[0] + box[2]) / 2 + pad, (box[1] + box[3]) / 2 + pad]
            new_img = pad_img[ct[1] - l / 2:ct[1] + l / 2, ct[0] - l / 2:ct[0] + l / 2].copy()
            new_img = cv2.resize(new_img, (SIZE, SIZE))
            v = viewpoint[i][0]
            a = v['azimuth'][0][0][0]
            e = v['elevation'][0][0][0]
            save_name = '{}/{}_{}'.format(obj_path, obj_id, cnt)
            cv2.imwrite(save_name + '.png', new_img)
            view_file.write('{} {} {}\n'.format(save_name, int(a), int(e)))
            cnt += 1

            #print 'a', viewpoint[i]['azimuth']
            #print 'a v', v['azimuth'][0]
            if DEBUG:
                cv2.imshow('new_img', new_img)
                cv2.waitKey()
                cv2.circle(img, (box[0], box[1]), 3, (255, 0, 0), -1)
                cv2.circle(img, (box[0], box[3]), 3, (255, 0, 0), -1)
                cv2.circle(img, (box[2], box[3]), 3, (255, 0, 0), -1)
                cv2.circle(img, (box[2], box[1]), 3, (255, 0, 0), -1)
                cv2.line(img, (box[0], box[1]), (box[0], box[3]), (255, 0, 0), 2)
                cv2.line(img, (box[0], box[1]), (box[2], box[1]), (255, 0, 0), 2)
                cv2.line(img, (box[2], box[3]), (box[0], box[3]), (255, 0, 0), 2)
                cv2.line(img, (box[2], box[3]), (box[2], box[1]), (255, 0, 0), 2)
        
        
        #break
    break

    
    

tvmonitor
tvmonitor
tvmonitor
person
person
chair
chair
bottle
bottle
bottle
chair
chair
sofa
bottle
person
chair
pottedplant
chair
chair
chair
chair
chair
chair
diningtable
sofa
bottle
bottle
tvmonitor
bottle
bottle
bottle
bottle
tvmonitor
person
person
person
chair
bottle
bottle
bottle
person
person
bottle
bottle
chair
chair
diningtable
bottle
bottle
diningtable
pottedplant
person
person
person
person
bottle
cat
bottle
pottedplant
pottedplant
pottedplant
pottedplant
pottedplant
bottle
bottle
bottle
bottle
bottle

/home/zxy/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:34: RuntimeWarning: overflow encountered in ubyte_scalars



bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
dog
bottle
person
pottedplant
dog
chair
person
bottle
car
car
person
bottle
person
diningtable
person
person
person
bottle
person
diningtable
chair
chair
bottle
pottedplant
pottedplant
pottedplant
bottle
bottle
diningtable
bottle
bottle
chair
person
pottedplant
pottedplant
pottedplant
bottle
bottle
chair
chair
diningtable
chair
bottle
diningtable
bottle
bicycle
bottle
person
bottle
person
chair
chair
chair
person
chair
bottle
bicycle
bottle
bottle
diningtable
bottle
bottle
bottle
person
sofa
bottle
bottle
bottle
bottle
bottle
person
bottle
bottle
diningtable
chair
diningtable
bottle
person
pottedplant
bottle
person
bottle
bottle
bottle
bottle
person
bottle
bottle
bottle
person
person
person
diningtable
chair
bottle
bottle
bottle
bottle
person
person
bottle
bottle
bottle
person
cat
sofa
bottle
bottle
bottle
chair
chair
diningtable
person
person
diningtable
chair
person
pottedplant
bottle
bottle
bottle
t

bottle
bottle
bottle
bottle
chair
diningtable
bottle
bottle
bottle
bottle
person
sheep
sheep
sheep
sheep
sheep
motorbike
motorbike
bottle
person
person
bottle
person
person
bottle
bottle
bottle
bottle
bottle
bottle
bottle
person
person
bottle
diningtable
chair
diningtable
person
chair
person
person
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
person
person
person
bottle
person
person
person
person
person
bottle
bottle
bottle
person
person
person
bottle
bottle
bottle
person
bottle
tvmonitor
bottle
bottle
bicycle
bicycle
person
person
bottle
diningtable
chair
person
chair
person
chair
chair
person
person
person
person
person
person
bottle
bottle
person
chair
bottle
person
person
person
diningtable
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
tvmonitor
bottle
person
bottle
person
person
bottle
chair
person
person
bottle
bottle
bottle
person
bottle
bottle
bottle
bottle
person
bottle
person
person
bottle
person
bottle
bo

person
person
bicycle
person
car
bottle
chair
chair
chair
chair
chair
chair
tvmonitor
diningtable
person
bottle
car
person
bottle
diningtable
chair
bottle
person
bottle
person
diningtable
bicycle
person
person
person
bottle
tvmonitor
tvmonitor
tvmonitor
person
person
person
bottle
diningtable
bottle
person
person
diningtable
diningtable
bottle
bottle
bicycle
person
bottle
chair
chair
chair
person
person
person
person
person
person
person
person
bottle
person
bottle
bottle
bottle
person
person
person
person
person
person
bottle
diningtable
bottle
person
person
person
bottle
chair
chair
chair
diningtable
chair
person
person
person
tvmonitor
person
bottle
bottle
bottle
bottle
bottle
tvmonitor
person
person
person
person
person
person
person
diningtable
chair
chair
tvmonitor
bottle
bottle
chair
chair
chair
chair
chair
chair
chair
chair
person
person
person
diningtable
diningtable
person
person
person
person
diningtable
bicycle
bottle
bottle
bottle
person
tvmonitor
pottedplant
pottedplant
b

person
bottle
person
bottle
chair
tvmonitor
person
person
bottle
bottle
person
bottle
person
chair
chair
person
person
person
person
person
diningtable
person
person
person
person
person
person
person
person
person
person
diningtable
bottle
person
person
bottle
person
person
dog
bottle
chair
person
bottle
bottle
bottle
bottle
bottle
bottle
person
bottle
bottle
bottle
person
person
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
bottle
diningtable
bottle
bottle
bottle
person
bottle
bottle
person
person
chair
sofa
bottle
bottle
bottle
person
person
chair
chair
chair
chair
bottle
person
person
person
diningtable
bottle
person
person
bottle
bottle
bottle
boat
boat
person
person
bottle
bottle
bottle
bottle
bottle
bottle
person
person
person
bottle
chair
person
bottle
car
person
person
person
person
tvmonitor
bottle
chair
bottle
sofa
perso

In [24]:
data_objects[0]

array([ array([[ (array([u'tvmonitor'], 
      dtype='<U9'), array([u'Left'], 
      dtype='<U4'), array([[1]], dtype=uint8), array([[0]], dtype=uint8), array([[0]], dtype=uint8), array([u'PAStvmonitorLeftTrunc'], 
      dtype='<U21'), array([u'PAStvmonitorLeftTrunc'], 
      dtype='<U21'), array([[233, 180, 277, 262]], dtype=uint16), array([[ (array([[233]], dtype=uint8), array([[180]], dtype=uint8), array([[277]], dtype=uint16), array([[262]], dtype=uint16))]], 
      dtype=[('xmin', 'O'), ('ymin', 'O'), ('xmax', 'O'), ('ymax', 'O')]), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([[0]], dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([[0]], dtype=uint8), array([], shape=(0, 0), dtype=uint8), array([], shape=(1, 0), dtype=float64), array([], shape=(1, 0), dtype=float64), array([], shape=(1, 0), dtype=float64)),
        (array([u'tvmonitor'], 
      dtype='<U9'), array([u'Left'], 
      dtype='<U4'), a

In [31]:
data['record']['objects'][0][0]['bbox']

array([[array([[233, 180, 277, 262]], dtype=uint16),
        array([[275, 181, 310, 274]], dtype=uint16),
        array([[119, 174, 140, 208]], dtype=uint8),
        array([[ 84, 190, 279, 434]], dtype=uint16),
        array([[ 39, 170, 113, 260]], dtype=uint16),
        array([[ 55, 288, 175, 455]], dtype=uint16),
        array([[ 25, 242,  94, 351]], dtype=uint16),
        array([[328, 279, 347, 340]], dtype=uint16),
        array([[338, 276, 352, 333]], dtype=uint16),
        array([[ 88, 207, 100, 234]], dtype=uint8)]], dtype=object)

In [32]:
data['record']['objects'][0][0]['viewpoint']

array([[array([], shape=(1, 0), dtype=float64),
        array([], shape=(1, 0), dtype=float64),
        array([], shape=(1, 0), dtype=float64),
        array([], shape=(1, 0), dtype=float64),
        array([], shape=(1, 0), dtype=float64),
        array([], shape=(1, 0), dtype=float64),
        array([], shape=(1, 0), dtype=float64),
        array([[ (array([[0]], dtype=uint8), array([[ 7.5]]), array([[  1.40407833e-05]]), array([[ 10.36039084]]), array([[ 46.78078117]]), array([[1]], dtype=uint8), array([[ 337.48725269]]), array([[ 306.63626577]]), array([[-1.29049621]]), array([[ 3.28926842]]), array([[ 1.62379178]]), array([[ 1.71021109]]), array([[7]], dtype=uint8), array([[3000]], dtype=uint16))]], 
      dtype=[('azimuth_coarse', 'O'), ('elevation_coarse', 'O'), ('azimuth', 'O'), ('elevation', 'O'), ('distance', 'O'), ('focal', 'O'), ('px', 'O'), ('py', 'O'), ('theta', 'O'), ('error', 'O'), ('interval_azimuth', 'O'), ('interval_elevation', 'O'), ('num_anchor', 'O'), ('viewport', 

In [33]:
print annot_file

/home/zxy/Datasets/pascal3d/Annotations/bottle_pascal/2008_003280
